export const TASKS = [
  "Attack Hired Hand with Webgun",
  "Attack Hired Hand with Shotgun",
  "Attack Hired Hand with Freeze Ray",
  "Attack Hired Hand with Clone Gun",
  "Attack Hired Hand with Crossbow",
  "Attack Hired Hand with Camera",
  "Attack Hired Hand with Boomerang",
  "Attack Hired Hand with Machete",
  "Attack Hired Hand with Excalibur",
  "Attack Hired Hand with Broken Sword",
  "Attack Hired Hand with Plasma Cannon",
  "Attack Hired Hand with Scepter",
  "Attack Hired Hand with Hou Yi's Bow",
  "Attack Hired Hand with Eggplant",
  "Attack Eggplant Child with Webgun",
  "Attack Eggplant Child with Shotgun",
  "Attack Eggplant Child with Freeze Ray",
  "Attack Eggplant Child with Clone Gun",
  "Attack Eggplant Child with Crossbow",
  "Attack Eggplant Child with Camera",
  "Attack Eggplant Child with Boomerang",
  "Attack Eggplant Child with Machete",
  "Attack Eggplant Child with Excalibur",
  "Attack Eggplant Child with Broken Sword",
  "Attack Eggplant Child with Plasma Cannon",
  "Attack Eggplant Child with Scepter",
  "Attack Eggplant Child with Hou Yi's Bow",
  "Attack Eggplant Child with Eggplant",
  "Attack Shopkeeper with Webgun",
  "Attack Shopkeeper with Shotgun",
  "Attack Shopkeeper with Freeze Ray",
  "Attack Shopkeeper with Clone Gun",
  "Attack Shopkeeper with Crossbow",
  "Attack Shopkeeper with Camera",
  "Attack Shopkeeper with Boomerang",
  "Attack Shopkeeper with Machete",
  "Attack Shopkeeper with Excalibur",
  "Attack Shopkeeper with Broken Sword",
  "Attack Shopkeeper with Plasma Cannon",
  "Attack Shopkeeper with Scepter",
  "Attack Shopkeeper with Hou Yi's Bow",
  "Attack Shopkeeper with Eggplant",
  "Attack Tun with Webgun",
  "Attack Tun with Shotgun",
  "Attack Tun with Freeze Ray",
  "Attack Tun with Clone Gun",
  "Attack Tun with Crossbow",
  "Attack Tun with Camera",
  "Attack Tun with Boomerang",
  "Attack Tun with Machete",
  "Attack Tun with Excalibur",
  "Attack Tun with Broken Sword",
  "Attack Tun with Plasma Cannon",
  "Attack Tun with Scepter",
  "Attack Tun with Hou Yi's Bow",
  "Attack Tun with Eggplant",
  "Attack Yang with Webgun",
  "Attack Yang with Shotgun",
  "Attack Yang with Freeze Ray",
  "Attack Yang with Clone Gun",
  "Attack Yang with Crossbow",
  "Attack Yang with Camera",
  "Attack Yang with Boomerang",
  "Attack Yang with Machete",
  "Attack Yang with Excalibur",
  "Attack Yang with Broken Sword",
  "Attack Yang with Plasma Cannon",
  "Attack Yang with Scepter",
  "Attack Yang with Hou Yi's Bow",
  "Attack Yang with Eggplant",
  "Attack Madame Tusk with Webgun",
  "Attack Madame Tusk with Shotgun",
  "Attack Madame Tusk with Freeze Ray",
  "Attack Madame Tusk with Clone Gun",
  "Attack Madame Tusk with Crossbow",
  "Attack Madame Tusk with Camera",
  "Attack Madame Tusk with Boomerang",
  "Attack Madame Tusk with Machete",
  "Attack Madame Tusk with Excalibur",
  "Attack Madame Tusk with Broken Sword",
  "Attack Madame Tusk with Plasma Cannon",
  "Attack Madame Tusk with Scepter",
  "Attack Madame Tusk with Hou Yi's Bow",
  "Attack Madame Tusk with Eggplant",
  "Attack Tusk's Bodyguard with Webgun",
  "Attack Tusk's Bodyguard with Shotgun",
  "Attack Tusk's Bodyguard with Freeze Ray",
  "Attack Tusk's Bodyguard with Clone Gun",
  "Attack Tusk's Bodyguard with Crossbow",
  "Attack Tusk's Bodyguard with Camera",
  "Attack Tusk's Bodyguard with Boomerang",
  "Attack Tusk's Bodyguard with Machete",
  "Attack Tusk's Bodyguard with Excalibur",
  "Attack Tusk's Bodyguard with Broken Sword",
  "Attack Tusk's Bodyguard with Plasma Cannon",
  "Attack Tusk's Bodyguard with Scepter",
  "Attack Tusk's Bodyguard with Hou Yi's Bow",
  "Attack Tusk's Bodyguard with Eggplant",
  "Attack Waddler with Webgun",
  "Attack Waddler with Shotgun",
  "Attack Waddler with Freeze Ray",
  "Attack Waddler with Clone Gun",
  "Attack Waddler with Crossbow",
  "Attack Waddler with Camera",
  "Attack Waddler with Boomerang",
  "Attack Waddler with Machete",
  "Attack Waddler with Excalibur",
  "Attack Waddler with Broken Sword",
  "Attack Waddler with Plasma Cannon",
  "Attack Waddler with Scepter",
  "Attack Waddler with Hou Yi's Bow",
  "Attack Waddler with Eggplant",
  "Attack Caveman Shopkeeper with Webgun",
  "Attack Caveman Shopkeeper with Shotgun",
  "Attack Caveman Shopkeeper with Freeze Ray",
  "Attack Caveman Shopkeeper with Clone Gun",
  "Attack Caveman Shopkeeper with Crossbow",
  "Attack Caveman Shopkeeper with Camera",
  "Attack Caveman Shopkeeper with Boomerang",
  "Attack Caveman Shopkeeper with Machete",
  "Attack Caveman Shopkeeper with Excalibur",
  "Attack Caveman Shopkeeper with Broken Sword",
  "Attack Caveman Shopkeeper with Plasma Cannon",
  "Attack Caveman Shopkeeper with Scepter",
  "Attack Caveman Shopkeeper with Hou Yi's Bow",
  "Attack Caveman Shopkeeper with Eggplant",
  "Attack Ghist Shopkeeper with Webgun",
  "Attack Ghist Shopkeeper with Shotgun",
  "Attack Ghist Shopkeeper with Freeze Ray",
  "Attack Ghist Shopkeeper with Clone Gun",
  "Attack Ghist Shopkeeper with Crossbow",
  "Attack Ghist Shopkeeper with Camera",
  "Attack Ghist Shopkeeper with Boomerang",
  "Attack Ghist Shopkeeper with Machete",
  "Attack Ghist Shopkeeper with Excalibur",
  "Attack Ghist Shopkeeper with Broken Sword",
  "Attack Ghist Shopkeeper with Plasma Cannon",
  "Attack Ghist Shopkeeper with Scepter",
  "Attack Ghist Shopkeeper with Hou Yi's Bow",
  "Attack Ghist Shopkeeper with Eggplant",
  "Attack Van Horsing with Webgun",
  "Attack Van Horsing with Shotgun",
  "Attack Van Horsing with Freeze Ray",
  "Attack Van Horsing with Clone Gun",
  "Attack Van Horsing with Crossbow",
  "Attack Van Horsing with Camera",
  "Attack Van Horsing with Boomerang",
  "Attack Van Horsing with Machete",
  "Attack Van Horsing with Excalibur",
  "Attack Van Horsing with Broken Sword",
  "Attack Van Horsing with Plasma Cannon",
  "Attack Van Horsing with Scepter",
  "Attack Van Horsing with Hou Yi's Bow",
  "Attack Van Horsing with Eggplant",
  "Attack Parsley with Webgun",
  "Attack Parsley with Shotgun",
  "Attack Parsley with Freeze Ray",
  "Attack Parsley with Clone Gun",
  "Attack Parsley with Crossbow",
  "Attack Parsley with Camera",
  "Attack Parsley with Boomerang",
  "Attack Parsley with Machete",
  "Attack Parsley with Excalibur",
  "Attack Parsley with Broken Sword",
  "Attack Parsley with Plasma Cannon",
  "Attack Parsley with Scepter",
  "Attack Parsley with Hou Yi's Bow",
  "Attack Parsley with Eggplant",
  "Attack Parsnip with Webgun",
  "Attack Parsnip with Shotgun",
  "Attack Parsnip with Freeze Ray",
  "Attack Parsnip with Clone Gun",
  "Attack Parsnip with Crossbow",
  "Attack Parsnip with Camera",
  "Attack Parsnip with Boomerang",
  "Attack Parsnip with Machete",
  "Attack Parsnip with Excalibur",
  "Attack Parsnip with Broken Sword",
  "Attack Parsnip with Plasma Cannon",
  "Attack Parsnip with Scepter",
  "Attack Parsnip with Hou Yi's Bow",
  "Attack Parsnip with Eggplant",
  "Attack Parmesan with Webgun",
  "Attack Parmesan with Shotgun",
  "Attack Parmesan with Freeze Ray",
  "Attack Parmesan with Clone Gun",
  "Attack Parmesan with Crossbow",
  "Attack Parmesan with Camera",
  "Attack Parmesan with Boomerang",
  "Attack Parmesan with Machete",
  "Attack Parmesan with Excalibur",
  "Attack Parmesan with Broken Sword",
  "Attack Parmesan with Plasma Cannon",
  "Attack Parmesan with Scepter",
  "Attack Parmesan with Hou Yi's Bow",
  "Attack Parmesan with Eggplant",
  "Attack Sparrow with Webgun",
  "Attack Sparrow with Shotgun",
  "Attack Sparrow with Freeze Ray",
  "Attack Sparrow with Clone Gun",
  "Attack Sparrow with Crossbow",
  "Attack Sparrow with Camera",
  "Attack Sparrow with Boomerang",
  "Attack Sparrow with Machete",
  "Attack Sparrow with Excalibur",
  "Attack Sparrow with Broken Sword",
  "Attack Sparrow with Plasma Cannon",
  "Attack Sparrow with Scepter",
  "Attack Sparrow with Hou Yi's Bow",
  "Attack Sparrow with Eggplant",
  "Attack Beg with Webgun",
  "Attack Beg with Shotgun",
  "Attack Beg with Freeze Ray",
  "Attack Beg with Clone Gun",
  "Attack Beg with Crossbow",
  "Attack Beg with Camera",
  "Attack Beg with Boomerang",
  "Attack Beg with Machete",
  "Attack Beg with Excalibur",
  "Attack Beg with Broken Sword",
  "Attack Beg with Plasma Cannon",
  "Attack Beg with Scepter",
  "Attack Beg with Hou Yi's Bow",
  "Attack Beg with Eggplant",
  "Attack Eggplant King with Webgun",
  "Attack Eggplant King with Shotgun",
  "Attack Eggplant King with Freeze Ray",
  "Attack Eggplant King with Clone Gun",
  "Attack Eggplant King with Crossbow",
  "Attack Eggplant King with Camera",
  "Attack Eggplant King with Boomerang",
  "Attack Eggplant King with Machete",
  "Attack Eggplant King with Excalibur",
  "Attack Eggplant King with Broken Sword",
  "Attack Eggplant King with Plasma Cannon",
  "Attack Eggplant King with Scepter",
  "Attack Eggplant King with Hou Yi's Bow",
  "Attack Eggplant King with Eggplant",
  "Feed Hired Hand to Mantrap",
  "Feed Eggplant Child to Mantrap",
  "Feed Shopkeeper to Mantrap",
  "Feed Tun to Mantrap",
  "Feed Yang to Mantrap",
  "Feed Caveman to Mantrap",
  "Feed Cave Mole to Mantrap",
  "Feed Tiki Man to Mantrap",
  "Feed Witch Doctor to Mantrap",
  "Feed Octopy to Mantrap",
  "Feed Hermit Crab to Mantrap",
  "Feed Crocman to Mantrap",
  "Feed Sorceress to Mantrap",
  "Feed Necromancer to Mantrap",
  "Feed Yeti to Mantrap",
  "Feed Olmite to Mantrap",
  "Feed Leprechaun to Mantrap",
  "Feed Pet to Mantrap",
  "Feed Cave Turkey to Mantrap",
  "Feed Rock Dog to Mantrap",
  "Feed Axolotl to Mantrap",
  "Feed Qilin to Mantrap",
  "Get 5k",
  "Get 10k",
  "Get 15k",
  "Get 20k",
  "Get 25k",
  "Get 30k",
  "Get 50k",
  "Get 100k",
  "Get 200k",
  "Get 500k",
  "Get 1M",
  "Kill Hired Hand",
  "Kill Eggplant Child",
  "Kill Shopkeeper",
  "Kill Tun",
  "Kill Yang",
  "Kill Madame Tusk",
  "Kill Tusk's Bodyguard",
  "Kill Waddler",
  "Kill Caveman Shopkeeper",
  "Kill Ghist Shopkeeper",
  "Kill Van Horsing",
  "Kill Parsley",
  "Kill Parsnip",
  "Kill Parmesan",
  "Kill Sparrow",
  "Kill Beg",
  "Kill Eggplant King",
  "Kill Hired Hand with Webgun",
  "Kill Hired Hand with Shotgun",
  "Kill Hired Hand with Freeze Ray",
  "Kill Hired Hand with Clone Gun",
  "Kill Hired Hand with Crossbow",
  "Kill Hired Hand with Camera",
  "Kill Hired Hand with Boomerang",
  "Kill Hired Hand with Machete",
  "Kill Hired Hand with Excalibur",
  "Kill Hired Hand with Broken Sword",
  "Kill Hired Hand with Plasma Cannon",
  "Kill Hired Hand with Scepter",
  "Kill Hired Hand with Hou Yi's Bow",
  "Kill Hired Hand with Eggplant",
  "Kill Eggplant Child with Webgun",
  "Kill Eggplant Child with Shotgun",
  "Kill Eggplant Child with Freeze Ray",
  "Kill Eggplant Child with Clone Gun",
  "Kill Eggplant Child with Crossbow",
  "Kill Eggplant Child with Camera",
  "Kill Eggplant Child with Boomerang",
  "Kill Eggplant Child with Machete",
  "Kill Eggplant Child with Excalibur",
  "Kill Eggplant Child with Broken Sword",
  "Kill Eggplant Child with Plasma Cannon",
  "Kill Eggplant Child with Scepter",
  "Kill Eggplant Child with Hou Yi's Bow",
  "Kill Eggplant Child with Eggplant",
  "Kill Shopkeeper with Webgun",
  "Kill Shopkeeper with Shotgun",
  "Kill Shopkeeper with Freeze Ray",
  "Kill Shopkeeper with Clone Gun",
  "Kill Shopkeeper with Crossbow",
  "Kill Shopkeeper with Camera",
  "Kill Shopkeeper with Boomerang",
  "Kill Shopkeeper with Machete",
  "Kill Shopkeeper with Excalibur",
  "Kill Shopkeeper with Broken Sword",
  "Kill Shopkeeper with Plasma Cannon",
  "Kill Shopkeeper with Scepter",
  "Kill Shopkeeper with Hou Yi's Bow",
  "Kill Shopkeeper with Eggplant",
  "Kill Tun with Webgun",
  "Kill Tun with Shotgun",
  "Kill Tun with Freeze Ray",
  "Kill Tun with Clone Gun",
  "Kill Tun with Crossbow",
  "Kill Tun with Camera",
  "Kill Tun with Boomerang",
  "Kill Tun with Machete",
  "Kill Tun with Excalibur",
  "Kill Tun with Broken Sword",
  "Kill Tun with Plasma Cannon",
  "Kill Tun with Scepter",
  "Kill Tun with Hou Yi's Bow",
  "Kill Tun with Eggplant",
  "Kill Yang with Webgun",
  "Kill Yang with Shotgun",
  "Kill Yang with Freeze Ray",
  "Kill Yang with Clone Gun",
  "Kill Yang with Crossbow",
  "Kill Yang with Camera",
  "Kill Yang with Boomerang",
  "Kill Yang with Machete",
  "Kill Yang with Excalibur",
  "Kill Yang with Broken Sword",
  "Kill Yang with Plasma Cannon",
  "Kill Yang with Scepter",
  "Kill Yang with Hou Yi's Bow",
  "Kill Yang with Eggplant",
  "Kill Madame Tusk with Webgun",
  "Kill Madame Tusk with Shotgun",
  "Kill Madame Tusk with Freeze Ray",
  "Kill Madame Tusk with Clone Gun",
  "Kill Madame Tusk with Crossbow",
  "Kill Madame Tusk with Camera",
  "Kill Madame Tusk with Boomerang",
  "Kill Madame Tusk with Machete",
  "Kill Madame Tusk with Excalibur",
  "Kill Madame Tusk with Broken Sword",
  "Kill Madame Tusk with Plasma Cannon",
  "Kill Madame Tusk with Scepter",
  "Kill Madame Tusk with Hou Yi's Bow",
  "Kill Madame Tusk with Eggplant",
  "Kill Tusk's Bodyguard with Webgun",
  "Kill Tusk's Bodyguard with Shotgun",
  "Kill Tusk's Bodyguard with Freeze Ray",
  "Kill Tusk's Bodyguard with Clone Gun",
  "Kill Tusk's Bodyguard with Crossbow",
  "Kill Tusk's Bodyguard with Camera",
  "Kill Tusk's Bodyguard with Boomerang",
  "Kill Tusk's Bodyguard with Machete",
  "Kill Tusk's Bodyguard with Excalibur",
  "Kill Tusk's Bodyguard with Broken Sword",
  "Kill Tusk's Bodyguard with Plasma Cannon",
  "Kill Tusk's Bodyguard with Scepter",
  "Kill Tusk's Bodyguard with Hou Yi's Bow",
  "Kill Tusk's Bodyguard with Eggplant",
  "Kill Waddler with Webgun",
  "Kill Waddler with Shotgun",
  "Kill Waddler with Freeze Ray",
  "Kill Waddler with Clone Gun",
  "Kill Waddler with Crossbow",
  "Kill Waddler with Camera",
  "Kill Waddler with Boomerang",
  "Kill Waddler with Machete",
  "Kill Waddler with Excalibur",
  "Kill Waddler with Broken Sword",
  "Kill Waddler with Plasma Cannon",
  "Kill Waddler with Scepter",
  "Kill Waddler with Hou Yi's Bow",
  "Kill Waddler with Eggplant",
  "Kill Caveman Shopkeeper with Webgun",
  "Kill Caveman Shopkeeper with Shotgun",
  "Kill Caveman Shopkeeper with Freeze Ray",
  "Kill Caveman Shopkeeper with Clone Gun",
  "Kill Caveman Shopkeeper with Crossbow",
  "Kill Caveman Shopkeeper with Camera",
  "Kill Caveman Shopkeeper with Boomerang",
  "Kill Caveman Shopkeeper with Machete",
  "Kill Caveman Shopkeeper with Excalibur",
  "Kill Caveman Shopkeeper with Broken Sword",
  "Kill Caveman Shopkeeper with Plasma Cannon",
  "Kill Caveman Shopkeeper with Scepter",
  "Kill Caveman Shopkeeper with Hou Yi's Bow",
  "Kill Caveman Shopkeeper with Eggplant",
  "Kill Ghist Shopkeeper with Webgun",
  "Kill Ghist Shopkeeper with Shotgun",
  "Kill Ghist Shopkeeper with Freeze Ray",
  "Kill Ghist Shopkeeper with Clone Gun",
  "Kill Ghist Shopkeeper with Crossbow",
  "Kill Ghist Shopkeeper with Camera",
  "Kill Ghist Shopkeeper with Boomerang",
  "Kill Ghist Shopkeeper with Machete",
  "Kill Ghist Shopkeeper with Excalibur",
  "Kill Ghist Shopkeeper with Broken Sword",
  "Kill Ghist Shopkeeper with Plasma Cannon",
  "Kill Ghist Shopkeeper with Scepter",
  "Kill Ghist Shopkeeper with Hou Yi's Bow",
  "Kill Ghist Shopkeeper with Eggplant",
  "Kill Van Horsing with Webgun",
  "Kill Van Horsing with Shotgun",
  "Kill Van Horsing with Freeze Ray",
  "Kill Van Horsing with Clone Gun",
  "Kill Van Horsing with Crossbow",
  "Kill Van Horsing with Camera",
  "Kill Van Horsing with Boomerang",
  "Kill Van Horsing with Machete",
  "Kill Van Horsing with Excalibur",
  "Kill Van Horsing with Broken Sword",
  "Kill Van Horsing with Plasma Cannon",
  "Kill Van Horsing with Scepter",
  "Kill Van Horsing with Hou Yi's Bow",
  "Kill Van Horsing with Eggplant",
  "Kill Parsley with Webgun",
  "Kill Parsley with Shotgun",
  "Kill Parsley with Freeze Ray",
  "Kill Parsley with Clone Gun",
  "Kill Parsley with Crossbow",
  "Kill Parsley with Camera",
  "Kill Parsley with Boomerang",
  "Kill Parsley with Machete",
  "Kill Parsley with Excalibur",
  "Kill Parsley with Broken Sword",
  "Kill Parsley with Plasma Cannon",
  "Kill Parsley with Scepter",
  "Kill Parsley with Hou Yi's Bow",
  "Kill Parsley with Eggplant",
  "Kill Parsnip with Webgun",
  "Kill Parsnip with Shotgun",
  "Kill Parsnip with Freeze Ray",
  "Kill Parsnip with Clone Gun",
  "Kill Parsnip with Crossbow",
  "Kill Parsnip with Camera",
  "Kill Parsnip with Boomerang",
  "Kill Parsnip with Machete",
  "Kill Parsnip with Excalibur",
  "Kill Parsnip with Broken Sword",
  "Kill Parsnip with Plasma Cannon",
  "Kill Parsnip with Scepter",
  "Kill Parsnip with Hou Yi's Bow",
  "Kill Parsnip with Eggplant",
  "Kill Parmesan with Webgun",
  "Kill Parmesan with Shotgun",
  "Kill Parmesan with Freeze Ray",
  "Kill Parmesan with Clone Gun",
  "Kill Parmesan with Crossbow",
  "Kill Parmesan with Camera",
  "Kill Parmesan with Boomerang",
  "Kill Parmesan with Machete",
  "Kill Parmesan with Excalibur",
  "Kill Parmesan with Broken Sword",
  "Kill Parmesan with Plasma Cannon",
  "Kill Parmesan with Scepter",
  "Kill Parmesan with Hou Yi's Bow",
  "Kill Parmesan with Eggplant",
  "Kill Sparrow with Webgun",
  "Kill Sparrow with Shotgun",
  "Kill Sparrow with Freeze Ray",
  "Kill Sparrow with Clone Gun",
  "Kill Sparrow with Crossbow",
  "Kill Sparrow with Camera",
  "Kill Sparrow with Boomerang",
  "Kill Sparrow with Machete",
  "Kill Sparrow with Excalibur",
  "Kill Sparrow with Broken Sword",
  "Kill Sparrow with Plasma Cannon",
  "Kill Sparrow with Scepter",
  "Kill Sparrow with Hou Yi's Bow",
  "Kill Sparrow with Eggplant",
  "Kill Beg with Webgun",
  "Kill Beg with Shotgun",
  "Kill Beg with Freeze Ray",
  "Kill Beg with Clone Gun",
  "Kill Beg with Crossbow",
  "Kill Beg with Camera",
  "Kill Beg with Boomerang",
  "Kill Beg with Machete",
  "Kill Beg with Excalibur",
  "Kill Beg with Broken Sword",
  "Kill Beg with Plasma Cannon",
  "Kill Beg with Scepter",
  "Kill Beg with Hou Yi's Bow",
  "Kill Beg with Eggplant",
  "Kill Eggplant King with Webgun",
  "Kill Eggplant King with Shotgun",
  "Kill Eggplant King with Freeze Ray",
  "Kill Eggplant King with Clone Gun",
  "Kill Eggplant King with Crossbow",
  "Kill Eggplant King with Camera",
  "Kill Eggplant King with Boomerang",
  "Kill Eggplant King with Machete",
  "Kill Eggplant King with Excalibur",
  "Kill Eggplant King with Broken Sword",
  "Kill Eggplant King with Plasma Cannon",
  "Kill Eggplant King with Scepter",
  "Kill Eggplant King with Hou Yi's Bow",
  "Kill Eggplant King with Eggplant",
  "Kill Hired Hand with Webgun",
  "Kill Hired Hand with Shotgun",
  "Kill Hired Hand with Freeze Ray",
  "Kill Hired Hand with Clone Gun",
  "Kill Hired Hand with Crossbow",
  "Kill Hired Hand with Camera",
  "Kill Hired Hand with Boomerang",
  "Kill Hired Hand with Machete",
  "Kill Hired Hand with Excalibur",
  "Kill Hired Hand with Broken Sword",
  "Kill Hired Hand with Plasma Cannon",
  "Kill Hired Hand with Scepter",
  "Kill Hired Hand with Hou Yi's Bow",
  "Kill Hired Hand with Eggplant",
  "Kill Eggplant Child with Webgun",
  "Kill Eggplant Child with Shotgun",
  "Kill Eggplant Child with Freeze Ray",
  "Kill Eggplant Child with Clone Gun",
  "Kill Eggplant Child with Crossbow",
  "Kill Eggplant Child with Camera",
  "Kill Eggplant Child with Boomerang",
  "Kill Eggplant Child with Machete",
  "Kill Eggplant Child with Excalibur",
  "Kill Eggplant Child with Broken Sword",
  "Kill Eggplant Child with Plasma Cannon",
  "Kill Eggplant Child with Scepter",
  "Kill Eggplant Child with Hou Yi's Bow",
  "Kill Eggplant Child with Eggplant",
  "Kill Shopkeeper with Webgun",
  "Kill Shopkeeper with Shotgun",
  "Kill Shopkeeper with Freeze Ray",
  "Kill Shopkeeper with Clone Gun",
  "Kill Shopkeeper with Crossbow",
  "Kill Shopkeeper with Camera",
  "Kill Shopkeeper with Boomerang",
  "Kill Shopkeeper with Machete",
  "Kill Shopkeeper with Excalibur",
  "Kill Shopkeeper with Broken Sword",
  "Kill Shopkeeper with Plasma Cannon",
  "Kill Shopkeeper with Scepter",
  "Kill Shopkeeper with Hou Yi's Bow",
  "Kill Shopkeeper with Eggplant",
  "Kill Tun with Webgun",
  "Kill Tun with Shotgun",
  "Kill Tun with Freeze Ray",
  "Kill Tun with Clone Gun",
  "Kill Tun with Crossbow",
  "Kill Tun with Camera",
  "Kill Tun with Boomerang",
  "Kill Tun with Machete",
  "Kill Tun with Excalibur",
  "Kill Tun with Broken Sword",
  "Kill Tun with Plasma Cannon",
  "Kill Tun with Scepter",
  "Kill Tun with Hou Yi's Bow",
  "Kill Tun with Eggplant",
  "Kill Yang with Webgun",
  "Kill Yang with Shotgun",
  "Kill Yang with Freeze Ray",
  "Kill Yang with Clone Gun",
  "Kill Yang with Crossbow",
  "Kill Yang with Camera",
  "Kill Yang with Boomerang",
  "Kill Yang with Machete",
  "Kill Yang with Excalibur",
  "Kill Yang with Broken Sword",
  "Kill Yang with Plasma Cannon",
  "Kill Yang with Scepter",
  "Kill Yang with Hou Yi's Bow",
  "Kill Yang with Eggplant",
  "Kill Madame Tusk with Webgun",
  "Kill Madame Tusk with Shotgun",
  "Kill Madame Tusk with Freeze Ray",
  "Kill Madame Tusk with Clone Gun",
  "Kill Madame Tusk with Crossbow",
  "Kill Madame Tusk with Camera",
  "Kill Madame Tusk with Boomerang",
  "Kill Madame Tusk with Machete",
  "Kill Madame Tusk with Excalibur",
  "Kill Madame Tusk with Broken Sword",
  "Kill Madame Tusk with Plasma Cannon",
  "Kill Madame Tusk with Scepter",
  "Kill Madame Tusk with Hou Yi's Bow",
  "Kill Madame Tusk with Eggplant",
  "Kill Tusk's Bodyguard with Webgun",
  "Kill Tusk's Bodyguard with Shotgun",
  "Kill Tusk's Bodyguard with Freeze Ray",
  "Kill Tusk's Bodyguard with Clone Gun",
  "Kill Tusk's Bodyguard with Crossbow",
  "Kill Tusk's Bodyguard with Camera",
  "Kill Tusk's Bodyguard with Boomerang",
  "Kill Tusk's Bodyguard with Machete",
  "Kill Tusk's Bodyguard with Excalibur",
  "Kill Tusk's Bodyguard with Broken Sword",
  "Kill Tusk's Bodyguard with Plasma Cannon",
  "Kill Tusk's Bodyguard with Scepter",
  "Kill Tusk's Bodyguard with Hou Yi's Bow",
  "Kill Tusk's Bodyguard with Eggplant",
  "Kill Waddler with Webgun",
  "Kill Waddler with Shotgun",
  "Kill Waddler with Freeze Ray",
  "Kill Waddler with Clone Gun",
  "Kill Waddler with Crossbow",
  "Kill Waddler with Camera",
  "Kill Waddler with Boomerang",
  "Kill Waddler with Machete",
  "Kill Waddler with Excalibur",
  "Kill Waddler with Broken Sword",
  "Kill Waddler with Plasma Cannon",
  "Kill Waddler with Scepter",
  "Kill Waddler with Hou Yi's Bow",
  "Kill Waddler with Eggplant",
  "Kill Caveman Shopkeeper with Webgun",
  "Kill Caveman Shopkeeper with Shotgun",
  "Kill Caveman Shopkeeper with Freeze Ray",
  "Kill Caveman Shopkeeper with Clone Gun",
  "Kill Caveman Shopkeeper with Crossbow",
  "Kill Caveman Shopkeeper with Camera",
  "Kill Caveman Shopkeeper with Boomerang",
  "Kill Caveman Shopkeeper with Machete",
  "Kill Caveman Shopkeeper with Excalibur",
  "Kill Caveman Shopkeeper with Broken Sword",
  "Kill Caveman Shopkeeper with Plasma Cannon",
  "Kill Caveman Shopkeeper with Scepter",
  "Kill Caveman Shopkeeper with Hou Yi's Bow",
  "Kill Caveman Shopkeeper with Eggplant",
  "Kill Ghist Shopkeeper with Webgun",
  "Kill Ghist Shopkeeper with Shotgun",
  "Kill Ghist Shopkeeper with Freeze Ray",
  "Kill Ghist Shopkeeper with Clone Gun",
  "Kill Ghist Shopkeeper with Crossbow",
  "Kill Ghist Shopkeeper with Camera",
  "Kill Ghist Shopkeeper with Boomerang",
  "Kill Ghist Shopkeeper with Machete",
  "Kill Ghist Shopkeeper with Excalibur",
  "Kill Ghist Shopkeeper with Broken Sword",
  "Kill Ghist Shopkeeper with Plasma Cannon",
  "Kill Ghist Shopkeeper with Scepter",
  "Kill Ghist Shopkeeper with Hou Yi's Bow",
  "Kill Ghist Shopkeeper with Eggplant",
  "Kill Van Horsing with Webgun",
  "Kill Van Horsing with Shotgun",
  "Kill Van Horsing with Freeze Ray",
  "Kill Van Horsing with Clone Gun",
  "Kill Van Horsing with Crossbow",
  "Kill Van Horsing with Camera",
  "Kill Van Horsing with Boomerang",
  "Kill Van Horsing with Machete",
  "Kill Van Horsing with Excalibur",
  "Kill Van Horsing with Broken Sword",
  "Kill Van Horsing with Plasma Cannon",
  "Kill Van Horsing with Scepter",
  "Kill Van Horsing with Hou Yi's Bow",
  "Kill Van Horsing with Eggplant",
  "Kill Parsley with Webgun",
  "Kill Parsley with Shotgun",
  "Kill Parsley with Freeze Ray",
  "Kill Parsley with Clone Gun",
  "Kill Parsley with Crossbow",
  "Kill Parsley with Camera",
  "Kill Parsley with Boomerang",
  "Kill Parsley with Machete",
  "Kill Parsley with Excalibur",
  "Kill Parsley with Broken Sword",
  "Kill Parsley with Plasma Cannon",
  "Kill Parsley with Scepter",
  "Kill Parsley with Hou Yi's Bow",
  "Kill Parsley with Eggplant",
  "Kill Parsnip with Webgun",
  "Kill Parsnip with Shotgun",
  "Kill Parsnip with Freeze Ray",
  "Kill Parsnip with Clone Gun",
  "Kill Parsnip with Crossbow",
  "Kill Parsnip with Camera",
  "Kill Parsnip with Boomerang",
  "Kill Parsnip with Machete",
  "Kill Parsnip with Excalibur",
  "Kill Parsnip with Broken Sword",
  "Kill Parsnip with Plasma Cannon",
  "Kill Parsnip with Scepter",
  "Kill Parsnip with Hou Yi's Bow",
  "Kill Parsnip with Eggplant",
  "Kill Parmesan with Webgun",
  "Kill Parmesan with Shotgun",
  "Kill Parmesan with Freeze Ray",
  "Kill Parmesan with Clone Gun",
  "Kill Parmesan with Crossbow",
  "Kill Parmesan with Camera",
  "Kill Parmesan with Boomerang",
  "Kill Parmesan with Machete",
  "Kill Parmesan with Excalibur",
  "Kill Parmesan with Broken Sword",
  "Kill Parmesan with Plasma Cannon",
  "Kill Parmesan with Scepter",
  "Kill Parmesan with Hou Yi's Bow",
  "Kill Parmesan with Eggplant",
  "Kill Sparrow with Webgun",
  "Kill Sparrow with Shotgun",
  "Kill Sparrow with Freeze Ray",
  "Kill Sparrow with Clone Gun",
  "Kill Sparrow with Crossbow",
  "Kill Sparrow with Camera",
  "Kill Sparrow with Boomerang",
  "Kill Sparrow with Machete",
  "Kill Sparrow with Excalibur",
  "Kill Sparrow with Broken Sword",
  "Kill Sparrow with Plasma Cannon",
  "Kill Sparrow with Scepter",
  "Kill Sparrow with Hou Yi's Bow",
  "Kill Sparrow with Eggplant",
  "Kill Beg with Webgun",
  "Kill Beg with Shotgun",
  "Kill Beg with Freeze Ray",
  "Kill Beg with Clone Gun",
  "Kill Beg with Crossbow",
  "Kill Beg with Camera",
  "Kill Beg with Boomerang",
  "Kill Beg with Machete",
  "Kill Beg with Excalibur",
  "Kill Beg with Broken Sword",
  "Kill Beg with Plasma Cannon",
  "Kill Beg with Scepter",
  "Kill Beg with Hou Yi's Bow",
  "Kill Beg with Eggplant",
  "Kill Eggplant King with Webgun",
  "Kill Eggplant King with Shotgun",
  "Kill Eggplant King with Freeze Ray",
  "Kill Eggplant King with Clone Gun",
  "Kill Eggplant King with Crossbow",
  "Kill Eggplant King with Camera",
  "Kill Eggplant King with Boomerang",
  "Kill Eggplant King with Machete",
  "Kill Eggplant King with Excalibur",
  "Kill Eggplant King with Broken Sword",
  "Kill Eggplant King with Plasma Cannon",
  "Kill Eggplant King with Scepter",
  "Kill Eggplant King with Hou Yi's Bow",
  "Kill Eggplant King with Eggplant",
  "Obtain Rope Pile",
  "Obtain Bomb Bag",
  "Obtain Bomb Box",
  "Obtain Paste",
  "Obtain Spectacles",
  "Obtain Climbing Gloves",
  "Obtain Pitcher's Mitt",
  "Obtain Spring Shoes",
  "Obtain Spike Shoes",
  "Obtain Compass",
  "Obtain Alien Compass",
  "Obtain Parachute",
  "Obtain Udjat Eye",
  "Obtain Kapala",
  "Obtain Hedjet",
  "Obtain Crown",
  "Obtain Eggplant Crown",
  "Obtain The True Crown",
  "Obtain Ankh",
  "Obtain Tablet Of Destiny",
  "Obtain Skeleton Key",
  "Obtain Royal Jelly",
  "Obtain Cape",
  "Obtain Vlad's Cape",
  "Obtain Jetpack",
  "Obtain Telepack",
  "Obtain Hoverpack",
  "Obtain Powerpack",
  "Obtain Webgun",
  "Obtain Shotgun",
  "Obtain Freeze Ray",
  "Obtain Clone Gun",
  "Obtain Crossbow",
  "Obtain Camera",
  "Obtain Teleporter",
  "Obtain Mattock",
  "Obtain Boomerang",
  "Obtain Machete",
  "Obtain Excalibur",
  "Obtain Broken Sword",
  "Obtain Plasma Cannon",
  "Obtain Scepter",
  "Obtain Hou Yi's Bow",
  "Obtain Arrow Of Light",
  "Obtain Wooden Shield",
  "Obtain Metal Shield",
  "Obtain Idol",
  "Obtain The Tusk Idol",
  "Obtain Curse Pot",
  "Obtain Ushabti",
  "Obtain Eggplant",
  "Obtain Cooked Turkey",
  "Obtain Elixir",
  "Obtain Four-leaf Clover",
  "Obtain Gold Key",
  "Obtain Big Chest",
  "Obtain Metal Key",
  "Obtain Stone Arrow",
  "Obtain Metal Arrow",
  "Obtain Broken Arrow",
  "Obtain Torch",
  "Obtain Scrap",
  "Obtain Ball and Chain",
  "Obtain Pot of Gold",
  "Obtain Dice",
  "Obtain Eggplant Flesh",
  "Obtain Corpse Bag",
  "Obtain Crate",
  "Obtain Present",
  "Obtain Chest",
  "Obtain Coffin",
  "Obtain Simple Clay Snake Ushabti",
  "Obtain Simple Clay Eye Ushabti",
  "Obtain Simple Clay Vortex Ushabti",
  "Obtain Simple Clay Ankh Ushabti",
  "Obtain Simple Clay Bat Ushabti",
  "Obtain Simple Wood Snake Ushabti",
  "Obtain Simple Wood Eye Ushabti",
  "Obtain Simple Wood Vortex Ushabti",
  "Obtain Simple Wood Ankh Ushabti",
  "Obtain Simple Wood Bat Ushabti",
  "Obtain Simple Gold Snake Ushabti",
  "Obtain Simple Gold Eye Ushabti",
  "Obtain Simple Gold Vortex Ushabti",
  "Obtain Simple Gold Ankh Ushabti",
  "Obtain Simple Gold Bat Ushabti",
  "Obtain Simple Jade Snake Ushabti",
  "Obtain Simple Jade Eye Ushabti",
  "Obtain Simple Jade Vortex Ushabti",
  "Obtain Simple Jade Ankh Ushabti",
  "Obtain Simple Jade Bat Ushabti",
  "Obtain Simple Onyx Snake Ushabti",
  "Obtain Simple Onyx Eye Ushabti",
  "Obtain Simple Onyx Vortex Ushabti",
  "Obtain Simple Onyx Ankh Ushabti",
  "Obtain Simple Onyx Bat Ushabti",
  "Obtain Tall Clay Snake Ushabti",
  "Obtain Tall Clay Eye Ushabti",
  "Obtain Tall Clay Vortex Ushabti",
  "Obtain Tall Clay Ankh Ushabti",
  "Obtain Tall Clay Bat Ushabti",
  "Obtain Tall Wood Snake Ushabti",
  "Obtain Tall Wood Eye Ushabti",
  "Obtain Tall Wood Vortex Ushabti",
  "Obtain Tall Wood Ankh Ushabti",
  "Obtain Tall Wood Bat Ushabti",
  "Obtain Tall Gold Snake Ushabti",
  "Obtain Tall Gold Eye Ushabti",
  "Obtain Tall Gold Vortex Ushabti",
  "Obtain Tall Gold Ankh Ushabti",
  "Obtain Tall Gold Bat Ushabti",
  "Obtain Tall Jade Snake Ushabti",
  "Obtain Tall Jade Eye Ushabti",
  "Obtain Tall Jade Vortex Ushabti",
  "Obtain Tall Jade Ankh Ushabti",
  "Obtain Tall Jade Bat Ushabti",
  "Obtain Tall Onyx Snake Ushabti",
  "Obtain Tall Onyx Eye Ushabti",
  "Obtain Tall Onyx Vortex Ushabti",
  "Obtain Tall Onyx Ankh Ushabti",
  "Obtain Tall Onyx Bat Ushabti",
  "Obtain Smiling Clay Snake Ushabti",
  "Obtain Smiling Clay Eye Ushabti",
  "Obtain Smiling Clay Vortex Ushabti",
  "Obtain Smiling Clay Ankh Ushabti",
  "Obtain Smiling Clay Bat Ushabti",
  "Obtain Smiling Wood Snake Ushabti",
  "Obtain Smiling Wood Eye Ushabti",
  "Obtain Smiling Wood Vortex Ushabti",
  "Obtain Smiling Wood Ankh Ushabti",
  "Obtain Smiling Wood Bat Ushabti",
  "Obtain Smiling Gold Snake Ushabti",
  "Obtain Smiling Gold Eye Ushabti",
  "Obtain Smiling Gold Vortex Ushabti",
  "Obtain Smiling Gold Ankh Ushabti",
  "Obtain Smiling Gold Bat Ushabti",
  "Obtain Smiling Jade Snake Ushabti",
  "Obtain Smiling Jade Eye Ushabti",
  "Obtain Smiling Jade Vortex Ushabti",
  "Obtain Smiling Jade Ankh Ushabti",
  "Obtain Smiling Jade Bat Ushabti",
  "Obtain Smiling Onyx Snake Ushabti",
  "Obtain Smiling Onyx Eye Ushabti",
  "Obtain Smiling Onyx Vortex Ushabti",
  "Obtain Smiling Onyx Ankh Ushabti",
  "Obtain Smiling Onyx Bat Ushabti",
  "Obtain Cracked Clay Snake Ushabti",
  "Obtain Cracked Clay Eye Ushabti",
  "Obtain Cracked Clay Vortex Ushabti",
  "Obtain Cracked Clay Ankh Ushabti",
  "Obtain Cracked Clay Bat Ushabti",
  "Obtain Cracked Wood Snake Ushabti",
  "Obtain Cracked Wood Eye Ushabti",
  "Obtain Cracked Wood Vortex Ushabti",
  "Obtain Cracked Wood Ankh Ushabti",
  "Obtain Cracked Wood Bat Ushabti",
  "Obtain Cracked Gold Snake Ushabti",
  "Obtain Cracked Gold Eye Ushabti",
  "Obtain Cracked Gold Vortex Ushabti",
  "Obtain Cracked Gold Ankh Ushabti",
  "Obtain Cracked Gold Bat Ushabti",
  "Obtain Cracked Jade Snake Ushabti",
  "Obtain Cracked Jade Eye Ushabti",
  "Obtain Cracked Jade Vortex Ushabti",
  "Obtain Cracked Jade Ankh Ushabti",
  "Obtain Cracked Jade Bat Ushabti",
  "Obtain Cracked Onyx Snake Ushabti",
  "Obtain Cracked Onyx Eye Ushabti",
  "Obtain Cracked Onyx Vortex Ushabti",
  "Obtain Cracked Onyx Ankh Ushabti",
  "Obtain Cracked Onyx Bat Ushabti",
  "Put Crossbow",
  "Put Hou Yi's Bow",
  "Put Wooden Shield",
  "Put Metal Shield",
  "Put Idol",
  "Put The Tusk Idol",
  "Put Curse Pot",
  "Put Ushabti",
  "Put Eggplant",
  "Put Gold Key",
  "Put Metal Key",
  "Put Stone Arrow",
  "Put Metal Arrow",
  "Put Broken Arrow",
  "Put Torch",
  "Put Ball and Chain",
  "Put Pot of Gold",
  "Put Dice",
  "Put Crate",
  "Put Present",
  "Put Chest",
  "Put Ball and Chain",
  "Sacrifice Caveman at the Kali altar",
  "Sacrifice Horned Lizard at the Kali altar",
  "Sacrifice Cave Mole at the Kali altar",
  "Sacrifice Mantrap at the Kali altar",
  "Sacrifice Tiki Man at the Kali altar",
  "Sacrifice Witch Doctor at the Kali altar",
  "Sacrifice Vampire at the Kali altar",
  "Sacrifice Octopy at the Kali altar",
  "Sacrifice Hermit Crab at the Kali altar",
  "Sacrifice Crocman at the Kali altar",
  "Sacrifice Sorceress at the Kali altar",
  "Sacrifice Necromancer at the Kali altar",
  "Sacrifice Yeti at the Kali altar",
  "Sacrifice Olmite at the Kali altar",
  "Sacrifice Scorpion at the Kali altar",
  "Sacrifice Leprechaun at the Kali altar",
  "Sacrifice Pet at the Kali altar",
  "Sacrifice Cave Turkey at the Kali altar",
  "Sacrifice Rock Dog at the Kali altar",
  "Sacrifice Axolotl at the Kali altar",
  "Sacrifice Qilin at the Kali altar",
  "Sacrifice Hired Hand at the Kali altar",
  "Sacrifice Eggplant Child at the Kali altar",
  "Sacrifice Shopkeeper at the Kali altar",
  "Sacrifice Tun at the Kali altar",
  "Sacrifice Yang at the Kali altar",
  "Sacrifice Tusk's Bodyguard at the Kali altar",
  "Sacrifice Beg at the Kali altar",
  "Throw Crossbow at Hired Hand",
  "Throw Crossbow at Eggplant Child",
  "Throw Crossbow at Shopkeeper",
  "Throw Crossbow at Tun",
  "Throw Crossbow at Yang",
  "Throw Crossbow at Madame Tusk",
  "Throw Crossbow at Tusk's Bodyguard",
  "Throw Crossbow at Waddler",
  "Throw Crossbow at Caveman Shopkeeper",
  "Throw Crossbow at Ghist Shopkeeper",
  "Throw Crossbow at Van Horsing",
  "Throw Crossbow at Parsley",
  "Throw Crossbow at Parsnip",
  "Throw Crossbow at Parmesan",
  "Throw Crossbow at Sparrow",
  "Throw Crossbow at Beg",
  "Throw Crossbow at Eggplant King",
  "Throw Hou Yi's Bow at Hired Hand",
  "Throw Hou Yi's Bow at Eggplant Child",
  "Throw Hou Yi's Bow at Shopkeeper",
  "Throw Hou Yi's Bow at Tun",
  "Throw Hou Yi's Bow at Yang",
  "Throw Hou Yi's Bow at Madame Tusk",
  "Throw Hou Yi's Bow at Tusk's Bodyguard",
  "Throw Hou Yi's Bow at Waddler",
  "Throw Hou Yi's Bow at Caveman Shopkeeper",
  "Throw Hou Yi's Bow at Ghist Shopkeeper",
  "Throw Hou Yi's Bow at Van Horsing",
  "Throw Hou Yi's Bow at Parsley",
  "Throw Hou Yi's Bow at Parsnip",
  "Throw Hou Yi's Bow at Parmesan",
  "Throw Hou Yi's Bow at Sparrow",
  "Throw Hou Yi's Bow at Beg",
  "Throw Hou Yi's Bow at Eggplant King",
  "Throw Wooden Shield at Hired Hand",
  "Throw Wooden Shield at Eggplant Child",
  "Throw Wooden Shield at Shopkeeper",
  "Throw Wooden Shield at Tun",
  "Throw Wooden Shield at Yang",
  "Throw Wooden Shield at Madame Tusk",
  "Throw Wooden Shield at Tusk's Bodyguard",
  "Throw Wooden Shield at Waddler",
  "Throw Wooden Shield at Caveman Shopkeeper",
  "Throw Wooden Shield at Ghist Shopkeeper",
  "Throw Wooden Shield at Van Horsing",
  "Throw Wooden Shield at Parsley",
  "Throw Wooden Shield at Parsnip",
  "Throw Wooden Shield at Parmesan",
  "Throw Wooden Shield at Sparrow",
  "Throw Wooden Shield at Beg",
  "Throw Wooden Shield at Eggplant King",
  "Throw Metal Shield at Hired Hand",
  "Throw Metal Shield at Eggplant Child",
  "Throw Metal Shield at Shopkeeper",
  "Throw Metal Shield at Tun",
  "Throw Metal Shield at Yang",
  "Throw Metal Shield at Madame Tusk",
  "Throw Metal Shield at Tusk's Bodyguard",
  "Throw Metal Shield at Waddler",
  "Throw Metal Shield at Caveman Shopkeeper",
  "Throw Metal Shield at Ghist Shopkeeper",
  "Throw Metal Shield at Van Horsing",
  "Throw Metal Shield at Parsley",
  "Throw Metal Shield at Parsnip",
  "Throw Metal Shield at Parmesan",
  "Throw Metal Shield at Sparrow",
  "Throw Metal Shield at Beg",
  "Throw Metal Shield at Eggplant King",
  "Throw Idol at Hired Hand",
  "Throw Idol at Eggplant Child",
  "Throw Idol at Shopkeeper",
  "Throw Idol at Tun",
  "Throw Idol at Yang",
  "Throw Idol at Madame Tusk",
  "Throw Idol at Tusk's Bodyguard",
  "Throw Idol at Waddler",
  "Throw Idol at Caveman Shopkeeper",
  "Throw Idol at Ghist Shopkeeper",
  "Throw Idol at Van Horsing",
  "Throw Idol at Parsley",
  "Throw Idol at Parsnip",
  "Throw Idol at Parmesan",
  "Throw Idol at Sparrow",
  "Throw Idol at Beg",
  "Throw Idol at Eggplant King",
  "Throw The Tusk Idol at Hired Hand",
  "Throw The Tusk Idol at Eggplant Child",
  "Throw The Tusk Idol at Shopkeeper",
  "Throw The Tusk Idol at Tun",
  "Throw The Tusk Idol at Yang",
  "Throw The Tusk Idol at Madame Tusk",
  "Throw The Tusk Idol at Tusk's Bodyguard",
  "Throw The Tusk Idol at Waddler",
  "Throw The Tusk Idol at Caveman Shopkeeper",
  "Throw The Tusk Idol at Ghist Shopkeeper",
  "Throw The Tusk Idol at Van Horsing",
  "Throw The Tusk Idol at Parsley",
  "Throw The Tusk Idol at Parsnip",
  "Throw The Tusk Idol at Parmesan",
  "Throw The Tusk Idol at Sparrow",
  "Throw The Tusk Idol at Beg",
  "Throw The Tusk Idol at Eggplant King",
  "Throw Curse Pot at Hired Hand",
  "Throw Curse Pot at Eggplant Child",
  "Throw Curse Pot at Shopkeeper",
  "Throw Curse Pot at Tun",
  "Throw Curse Pot at Yang",
  "Throw Curse Pot at Madame Tusk",
  "Throw Curse Pot at Tusk's Bodyguard",
  "Throw Curse Pot at Waddler",
  "Throw Curse Pot at Caveman Shopkeeper",
  "Throw Curse Pot at Ghist Shopkeeper",
  "Throw Curse Pot at Van Horsing",
  "Throw Curse Pot at Parsley",
  "Throw Curse Pot at Parsnip",
  "Throw Curse Pot at Parmesan",
  "Throw Curse Pot at Sparrow",
  "Throw Curse Pot at Beg",
  "Throw Curse Pot at Eggplant King",
  "Throw Ushabti at Hired Hand",
  "Throw Ushabti at Eggplant Child",
  "Throw Ushabti at Shopkeeper",
  "Throw Ushabti at Tun",
  "Throw Ushabti at Yang",
  "Throw Ushabti at Madame Tusk",
  "Throw Ushabti at Tusk's Bodyguard",
  "Throw Ushabti at Waddler",
  "Throw Ushabti at Caveman Shopkeeper",
  "Throw Ushabti at Ghist Shopkeeper",
  "Throw Ushabti at Van Horsing",
  "Throw Ushabti at Parsley",
  "Throw Ushabti at Parsnip",
  "Throw Ushabti at Parmesan",
  "Throw Ushabti at Sparrow",
  "Throw Ushabti at Beg",
  "Throw Ushabti at Eggplant King",
  "Throw Eggplant at Hired Hand",
  "Throw Eggplant at Eggplant Child",
  "Throw Eggplant at Shopkeeper",
  "Throw Eggplant at Tun",
  "Throw Eggplant at Yang",
  "Throw Eggplant at Madame Tusk",
  "Throw Eggplant at Tusk's Bodyguard",
  "Throw Eggplant at Waddler",
  "Throw Eggplant at Caveman Shopkeeper",
  "Throw Eggplant at Ghist Shopkeeper",
  "Throw Eggplant at Van Horsing",
  "Throw Eggplant at Parsley",
  "Throw Eggplant at Parsnip",
  "Throw Eggplant at Parmesan",
  "Throw Eggplant at Sparrow",
  "Throw Eggplant at Beg",
  "Throw Eggplant at Eggplant King",
  "Throw Gold Key at Hired Hand",
  "Throw Gold Key at Eggplant Child",
  "Throw Gold Key at Shopkeeper",
  "Throw Gold Key at Tun",
  "Throw Gold Key at Yang",
  "Throw Gold Key at Madame Tusk",
  "Throw Gold Key at Tusk's Bodyguard",
  "Throw Gold Key at Waddler",
  "Throw Gold Key at Caveman Shopkeeper",
  "Throw Gold Key at Ghist Shopkeeper",
  "Throw Gold Key at Van Horsing",
  "Throw Gold Key at Parsley",
  "Throw Gold Key at Parsnip",
  "Throw Gold Key at Parmesan",
  "Throw Gold Key at Sparrow",
  "Throw Gold Key at Beg",
  "Throw Gold Key at Eggplant King",
  "Throw Metal Key at Hired Hand",
  "Throw Metal Key at Eggplant Child",
  "Throw Metal Key at Shopkeeper",
  "Throw Metal Key at Tun",
  "Throw Metal Key at Yang",
  "Throw Metal Key at Madame Tusk",
  "Throw Metal Key at Tusk's Bodyguard",
  "Throw Metal Key at Waddler",
  "Throw Metal Key at Caveman Shopkeeper",
  "Throw Metal Key at Ghist Shopkeeper",
  "Throw Metal Key at Van Horsing",
  "Throw Metal Key at Parsley",
  "Throw Metal Key at Parsnip",
  "Throw Metal Key at Parmesan",
  "Throw Metal Key at Sparrow",
  "Throw Metal Key at Beg",
  "Throw Metal Key at Eggplant King",
  "Throw Stone Arrow at Hired Hand",
  "Throw Stone Arrow at Eggplant Child",
  "Throw Stone Arrow at Shopkeeper",
  "Throw Stone Arrow at Tun",
  "Throw Stone Arrow at Yang",
  "Throw Stone Arrow at Madame Tusk",
  "Throw Stone Arrow at Tusk's Bodyguard",
  "Throw Stone Arrow at Waddler",
  "Throw Stone Arrow at Caveman Shopkeeper",
  "Throw Stone Arrow at Ghist Shopkeeper",
  "Throw Stone Arrow at Van Horsing",
  "Throw Stone Arrow at Parsley",
  "Throw Stone Arrow at Parsnip",
  "Throw Stone Arrow at Parmesan",
  "Throw Stone Arrow at Sparrow",
  "Throw Stone Arrow at Beg",
  "Throw Stone Arrow at Eggplant King",
  "Throw Metal Arrow at Hired Hand",
  "Throw Metal Arrow at Eggplant Child",
  "Throw Metal Arrow at Shopkeeper",
  "Throw Metal Arrow at Tun",
  "Throw Metal Arrow at Yang",
  "Throw Metal Arrow at Madame Tusk",
  "Throw Metal Arrow at Tusk's Bodyguard",
  "Throw Metal Arrow at Waddler",
  "Throw Metal Arrow at Caveman Shopkeeper",
  "Throw Metal Arrow at Ghist Shopkeeper",
  "Throw Metal Arrow at Van Horsing",
  "Throw Metal Arrow at Parsley",
  "Throw Metal Arrow at Parsnip",
  "Throw Metal Arrow at Parmesan",
  "Throw Metal Arrow at Sparrow",
  "Throw Metal Arrow at Beg",
  "Throw Metal Arrow at Eggplant King",
  "Throw Broken Arrow at Hired Hand",
  "Throw Broken Arrow at Eggplant Child",
  "Throw Broken Arrow at Shopkeeper",
  "Throw Broken Arrow at Tun",
  "Throw Broken Arrow at Yang",
  "Throw Broken Arrow at Madame Tusk",
  "Throw Broken Arrow at Tusk's Bodyguard",
  "Throw Broken Arrow at Waddler",
  "Throw Broken Arrow at Caveman Shopkeeper",
  "Throw Broken Arrow at Ghist Shopkeeper",
  "Throw Broken Arrow at Van Horsing",
  "Throw Broken Arrow at Parsley",
  "Throw Broken Arrow at Parsnip",
  "Throw Broken Arrow at Parmesan",
  "Throw Broken Arrow at Sparrow",
  "Throw Broken Arrow at Beg",
  "Throw Broken Arrow at Eggplant King",
  "Throw Torch at Hired Hand",
  "Throw Torch at Eggplant Child",
  "Throw Torch at Shopkeeper",
  "Throw Torch at Tun",
  "Throw Torch at Yang",
  "Throw Torch at Madame Tusk",
  "Throw Torch at Tusk's Bodyguard",
  "Throw Torch at Waddler",
  "Throw Torch at Caveman Shopkeeper",
  "Throw Torch at Ghist Shopkeeper",
  "Throw Torch at Van Horsing",
  "Throw Torch at Parsley",
  "Throw Torch at Parsnip",
  "Throw Torch at Parmesan",
  "Throw Torch at Sparrow",
  "Throw Torch at Beg",
  "Throw Torch at Eggplant King",
  "Throw Ball and Chain at Hired Hand",
  "Throw Ball and Chain at Eggplant Child",
  "Throw Ball and Chain at Shopkeeper",
  "Throw Ball and Chain at Tun",
  "Throw Ball and Chain at Yang",
  "Throw Ball and Chain at Madame Tusk",
  "Throw Ball and Chain at Tusk's Bodyguard",
  "Throw Ball and Chain at Waddler",
  "Throw Ball and Chain at Caveman Shopkeeper",
  "Throw Ball and Chain at Ghist Shopkeeper",
  "Throw Ball and Chain at Van Horsing",
  "Throw Ball and Chain at Parsley",
  "Throw Ball and Chain at Parsnip",
  "Throw Ball and Chain at Parmesan",
  "Throw Ball and Chain at Sparrow",
  "Throw Ball and Chain at Beg",
  "Throw Ball and Chain at Eggplant King",
  "Throw Pot of Gold at Hired Hand",
  "Throw Pot of Gold at Eggplant Child",
  "Throw Pot of Gold at Shopkeeper",
  "Throw Pot of Gold at Tun",
  "Throw Pot of Gold at Yang",
  "Throw Pot of Gold at Madame Tusk",
  "Throw Pot of Gold at Tusk's Bodyguard",
  "Throw Pot of Gold at Waddler",
  "Throw Pot of Gold at Caveman Shopkeeper",
  "Throw Pot of Gold at Ghist Shopkeeper",
  "Throw Pot of Gold at Van Horsing",
  "Throw Pot of Gold at Parsley",
  "Throw Pot of Gold at Parsnip",
  "Throw Pot of Gold at Parmesan",
  "Throw Pot of Gold at Sparrow",
  "Throw Pot of Gold at Beg",
  "Throw Pot of Gold at Eggplant King",
  "Throw Dice at Hired Hand",
  "Throw Dice at Eggplant Child",
  "Throw Dice at Shopkeeper",
  "Throw Dice at Tun",
  "Throw Dice at Yang",
  "Throw Dice at Madame Tusk",
  "Throw Dice at Tusk's Bodyguard",
  "Throw Dice at Waddler",
  "Throw Dice at Caveman Shopkeeper",
  "Throw Dice at Ghist Shopkeeper",
  "Throw Dice at Van Horsing",
  "Throw Dice at Parsley",
  "Throw Dice at Parsnip",
  "Throw Dice at Parmesan",
  "Throw Dice at Sparrow",
  "Throw Dice at Beg",
  "Throw Dice at Eggplant King",
  "Throw Crate at Hired Hand",
  "Throw Crate at Eggplant Child",
  "Throw Crate at Shopkeeper",
  "Throw Crate at Tun",
  "Throw Crate at Yang",
  "Throw Crate at Madame Tusk",
  "Throw Crate at Tusk's Bodyguard",
  "Throw Crate at Waddler",
  "Throw Crate at Caveman Shopkeeper",
  "Throw Crate at Ghist Shopkeeper",
  "Throw Crate at Van Horsing",
  "Throw Crate at Parsley",
  "Throw Crate at Parsnip",
  "Throw Crate at Parmesan",
  "Throw Crate at Sparrow",
  "Throw Crate at Beg",
  "Throw Crate at Eggplant King",
  "Throw Present at Hired Hand",
  "Throw Present at Eggplant Child",
  "Throw Present at Shopkeeper",
  "Throw Present at Tun",
  "Throw Present at Yang",
  "Throw Present at Madame Tusk",
  "Throw Present at Tusk's Bodyguard",
  "Throw Present at Waddler",
  "Throw Present at Caveman Shopkeeper",
  "Throw Present at Ghist Shopkeeper",
  "Throw Present at Van Horsing",
  "Throw Present at Parsley",
  "Throw Present at Parsnip",
  "Throw Present at Parmesan",
  "Throw Present at Sparrow",
  "Throw Present at Beg",
  "Throw Present at Eggplant King",
  "Throw Chest at Hired Hand",
  "Throw Chest at Eggplant Child",
  "Throw Chest at Shopkeeper",
  "Throw Chest at Tun",
  "Throw Chest at Yang",
  "Throw Chest at Madame Tusk",
  "Throw Chest at Tusk's Bodyguard",
  "Throw Chest at Waddler",
  "Throw Chest at Caveman Shopkeeper",
  "Throw Chest at Ghist Shopkeeper",
  "Throw Chest at Van Horsing",
  "Throw Chest at Parsley",
  "Throw Chest at Parsnip",
  "Throw Chest at Parmesan",
  "Throw Chest at Sparrow",
  "Throw Chest at Beg",
  "Throw Chest at Eggplant King",
  "Throw Ball and Chain at Hired Hand",
  "Throw Ball and Chain at Eggplant Child",
  "Throw Ball and Chain at Shopkeeper",
  "Throw Ball and Chain at Tun",
  "Throw Ball and Chain at Yang",
  "Throw Ball and Chain at Madame Tusk",
  "Throw Ball and Chain at Tusk's Bodyguard",
  "Throw Ball and Chain at Waddler",
  "Throw Ball and Chain at Caveman Shopkeeper",
  "Throw Ball and Chain at Ghist Shopkeeper",
  "Throw Ball and Chain at Van Horsing",
  "Throw Ball and Chain at Parsley",
  "Throw Ball and Chain at Parsnip",
  "Throw Ball and Chain at Parmesan",
  "Throw Ball and Chain at Sparrow",
  "Throw Ball and Chain at Beg",
  "Throw Ball and Chain at Eggplant King",
  "Rescue Yang's turkeys",
  "Buy out Yang's turkey shop",
  "Rescue Parsley",
  "Rescue Parsnip",
  "Rescue Parmesan",
  "Rescue all salad sisters and meet them at Olmec",
  "Rescue Van Horsing",
  "Help Van Horsing kill Vlad",
  "Return metal arrow to Van Horsing",
  "Meet Madame Tusk in Palace of Pleasure",
  "Get rope bag from Sparrow in Palace of Pleasure",
  "Give Cape to Caveman",
  "Give Vlad's Cape to Caveman",
  "Give Jetpack to Caveman",
  "Give Telepack to Caveman",
  "Give Hoverpack to Caveman",
  "Give Powerpack to Caveman",
  "Give Webgun to Caveman",
  "Give Shotgun to Caveman",
  "Give Freeze Ray to Caveman",
  "Give Clone Gun to Caveman",
  "Give Crossbow to Caveman",
  "Give Camera to Caveman",
  "Give Boomerang to Caveman",
  "Give Machete to Caveman",
  "Give Excalibur to Caveman",
  "Give Broken Sword to Caveman",
  "Give Plasma Cannon to Caveman",
  "Give Scepter to Caveman",
  "Give Hou Yi's Bow to Caveman",
  "Give Eggplant to Caveman",
  "Give Crossbow to Caveman",
  "Give Hou Yi's Bow to Caveman",
  "Give Wooden Shield to Caveman",
  "Give Metal Shield to Caveman",
  "Give Idol to Caveman",
  "Give The Tusk Idol to Caveman",
  "Give Curse Pot to Caveman",
  "Give Ushabti to Caveman",
  "Give Eggplant to Caveman",
  "Give Gold Key to Caveman",
  "Give Metal Key to Caveman",
  "Give Stone Arrow to Caveman",
  "Give Metal Arrow to Caveman",
  "Give Broken Arrow to Caveman",
  "Give Torch to Caveman",
  "Give Ball and Chain to Caveman",
  "Give Pot of Gold to Caveman",
  "Give Dice to Caveman",
  "Give Crate to Caveman",
  "Give Present to Caveman",
  "Give Chest to Caveman",
  "Give Ball and Chain to Caveman",
  "Finish Dwelling without picking up gold",
  "Finish Jungle without picking up gold",
  "Finish Volcana without picking up gold",
  "Finish Olmec's Lair without picking up gold",
  "Finish Tide Pool without picking up gold",
  "Finish Abzu without picking up gold",
  "Finish Temple of Anubis without picking up gold",
  "Finish The City of Gold without picking up gold",
  "Finish Duat without picking up gold",
  "Finish Ice Caves without picking up gold",
  "Finish Neo Babylon without picking up gold",
  "Finish Tiamat's Throne without picking up gold",
  "Finish Sunken City without picking up gold",
  "Finish Eggplant World without picking up gold",
  "Finish Hundun's Hideaway without picking up gold",
  "Finish Cosmic Ocean without picking up gold",
  "Finish Dwelling without killing enemies",
  "Finish Jungle without killing enemies",
  "Finish Volcana without killing enemies",
  "Finish Olmec's Lair without killing enemies",
  "Finish Tide Pool without killing enemies",
  "Finish Abzu without killing enemies",
  "Finish Temple of Anubis without killing enemies",
  "Finish The City of Gold without killing enemies",
  "Finish Duat without killing enemies",
  "Finish Ice Caves without killing enemies",
  "Finish Neo Babylon without killing enemies",
  "Finish Tiamat's Throne without killing enemies",
  "Finish Sunken City without killing enemies",
  "Finish Eggplant World without killing enemies",
  "Finish Hundun's Hideaway without killing enemies",
  "Finish Cosmic Ocean without killing enemies",
  "Drop Cape on Snake",
  "Drop Cape on Spider",
  "Drop Cape on Bat",
  "Drop Cape on Caveman",
  "Drop Cape on Skeleton",
  "Drop Cape on Horned Lizard",
  "Drop Cape on Cave Mole",
  "Drop Cape on Quillback",
  "Drop Cape on Mantrap",
  "Drop Cape on Tiki Man",
  "Drop Cape on Witch Doctor",
  "Drop Cape on Mosquito",
  "Drop Cape on Monkey",
  "Drop Cape on Hang Spider",
  "Drop Cape on Giant Spider",
  "Drop Cape on Fire Bug",
  "Drop Cape on Imp",
  "Drop Cape on Vampire",
  "Drop Cape on Vlad",
  "Drop Cape on Jiangshi",
  "Drop Cape on Jiangshi Assassin",
  "Drop Cape on Flying Fish",
  "Drop Cape on Octopy",
  "Drop Cape on Hermit Crab",
  "Drop Cape on Pangxie",
  "Drop Cape on Great Humphead",
  "Drop Cape on Crocman",
  "Drop Cape on Cobra",
  "Drop Cape on Mummy",
  "Drop Cape on Sorceress",
  "Drop Cape on Cat Mummy",
  "Drop Cape on Necromancer",
  "Drop Cape on Anubis",
  "Drop Cape on UFO",
  "Drop Cape on Alien",
  "Drop Cape on Yeti",
  "Drop Cape on Yeti King",
  "Drop Cape on Yeti Queen",
  "Drop Cape on Lahamu",
  "Drop Cape on Olmite",
  "Drop Cape on Lamassu",
  "Drop Cape on Tiamat",
  "Drop Cape on Tadpole",
  "Drop Cape on Frog",
  "Drop Cape on Fire Frog",
  "Drop Cape on Goliath Frog",
  "Drop Cape on Grub",
  "Drop Cape on Giant Fly",
  "Drop Cape on Hundun",
  "Drop Cape on Eggplant Minister",
  "Drop Cape on Eggplup",
  "Drop Cape on Scorpion",
  "Drop Cape on Bee",
  "Drop Cape on Queen Bee",
  "Drop Cape on Scarab",
  "Drop Cape on Golden Monkey",
  "Drop Cape on Leprechaun",
  "Drop Cape on Pet",
  "Drop Cape on Cave Turkey",
  "Drop Cape on Rock Dog",
  "Drop Cape on Axolotl",
  "Drop Cape on Qilin",
  "Drop Vlad's Cape on Snake",
  "Drop Vlad's Cape on Spider",
  "Drop Vlad's Cape on Bat",
  "Drop Vlad's Cape on Caveman",
  "Drop Vlad's Cape on Skeleton",
  "Drop Vlad's Cape on Horned Lizard",
  "Drop Vlad's Cape on Cave Mole",
  "Drop Vlad's Cape on Quillback",
  "Drop Vlad's Cape on Mantrap",
  "Drop Vlad's Cape on Tiki Man",
  "Drop Vlad's Cape on Witch Doctor",
  "Drop Vlad's Cape on Mosquito",
  "Drop Vlad's Cape on Monkey",
  "Drop Vlad's Cape on Hang Spider",
  "Drop Vlad's Cape on Giant Spider",
  "Drop Vlad's Cape on Fire Bug",
  "Drop Vlad's Cape on Imp",
  "Drop Vlad's Cape on Vampire",
  "Drop Vlad's Cape on Vlad",
  "Drop Vlad's Cape on Jiangshi",
  "Drop Vlad's Cape on Jiangshi Assassin",
  "Drop Vlad's Cape on Flying Fish",
  "Drop Vlad's Cape on Octopy",
  "Drop Vlad's Cape on Hermit Crab",
  "Drop Vlad's Cape on Pangxie",
  "Drop Vlad's Cape on Great Humphead",
  "Drop Vlad's Cape on Crocman",
  "Drop Vlad's Cape on Cobra",
  "Drop Vlad's Cape on Mummy",
  "Drop Vlad's Cape on Sorceress",
  "Drop Vlad's Cape on Cat Mummy",
  "Drop Vlad's Cape on Necromancer",
  "Drop Vlad's Cape on Anubis",
  "Drop Vlad's Cape on UFO",
  "Drop Vlad's Cape on Alien",
  "Drop Vlad's Cape on Yeti",
  "Drop Vlad's Cape on Yeti King",
  "Drop Vlad's Cape on Yeti Queen",
  "Drop Vlad's Cape on Lahamu",
  "Drop Vlad's Cape on Olmite",
  "Drop Vlad's Cape on Lamassu",
  "Drop Vlad's Cape on Tiamat",
  "Drop Vlad's Cape on Tadpole",
  "Drop Vlad's Cape on Frog",
  "Drop Vlad's Cape on Fire Frog",
  "Drop Vlad's Cape on Goliath Frog",
  "Drop Vlad's Cape on Grub",
  "Drop Vlad's Cape on Giant Fly",
  "Drop Vlad's Cape on Hundun",
  "Drop Vlad's Cape on Eggplant Minister",
  "Drop Vlad's Cape on Eggplup",
  "Drop Vlad's Cape on Scorpion",
  "Drop Vlad's Cape on Bee",
  "Drop Vlad's Cape on Queen Bee",
  "Drop Vlad's Cape on Scarab",
  "Drop Vlad's Cape on Golden Monkey",
  "Drop Vlad's Cape on Leprechaun",
  "Drop Vlad's Cape on Pet",
  "Drop Vlad's Cape on Cave Turkey",
  "Drop Vlad's Cape on Rock Dog",
  "Drop Vlad's Cape on Axolotl",
  "Drop Vlad's Cape on Qilin",
  "Drop Jetpack on Snake",
  "Drop Jetpack on Spider",
  "Drop Jetpack on Bat",
  "Drop Jetpack on Caveman",
  "Drop Jetpack on Skeleton",
  "Drop Jetpack on Horned Lizard",
  "Drop Jetpack on Cave Mole",
  "Drop Jetpack on Quillback",
  "Drop Jetpack on Mantrap",
  "Drop Jetpack on Tiki Man",
  "Drop Jetpack on Witch Doctor",
  "Drop Jetpack on Mosquito",
  "Drop Jetpack on Monkey",
  "Drop Jetpack on Hang Spider",
  "Drop Jetpack on Giant Spider",
  "Drop Jetpack on Fire Bug",
  "Drop Jetpack on Imp",
  "Drop Jetpack on Vampire",
  "Drop Jetpack on Vlad",
  "Drop Jetpack on Jiangshi",
  "Drop Jetpack on Jiangshi Assassin",
  "Drop Jetpack on Flying Fish",
  "Drop Jetpack on Octopy",
  "Drop Jetpack on Hermit Crab",
  "Drop Jetpack on Pangxie",
  "Drop Jetpack on Great Humphead",
  "Drop Jetpack on Crocman",
  "Drop Jetpack on Cobra",
  "Drop Jetpack on Mummy",
  "Drop Jetpack on Sorceress",
  "Drop Jetpack on Cat Mummy",
  "Drop Jetpack on Necromancer",
  "Drop Jetpack on Anubis",
  "Drop Jetpack on UFO",
  "Drop Jetpack on Alien",
  "Drop Jetpack on Yeti",
  "Drop Jetpack on Yeti King",
  "Drop Jetpack on Yeti Queen",
  "Drop Jetpack on Lahamu",
  "Drop Jetpack on Olmite",
  "Drop Jetpack on Lamassu",
  "Drop Jetpack on Tiamat",
  "Drop Jetpack on Tadpole",
  "Drop Jetpack on Frog",
  "Drop Jetpack on Fire Frog",
  "Drop Jetpack on Goliath Frog",
  "Drop Jetpack on Grub",
  "Drop Jetpack on Giant Fly",
  "Drop Jetpack on Hundun",
  "Drop Jetpack on Eggplant Minister",
  "Drop Jetpack on Eggplup",
  "Drop Jetpack on Scorpion",
  "Drop Jetpack on Bee",
  "Drop Jetpack on Queen Bee",
  "Drop Jetpack on Scarab",
  "Drop Jetpack on Golden Monkey",
  "Drop Jetpack on Leprechaun",
  "Drop Jetpack on Pet",
  "Drop Jetpack on Cave Turkey",
  "Drop Jetpack on Rock Dog",
  "Drop Jetpack on Axolotl",
  "Drop Jetpack on Qilin",
  "Drop Telepack on Snake",
  "Drop Telepack on Spider",
  "Drop Telepack on Bat",
  "Drop Telepack on Caveman",
  "Drop Telepack on Skeleton",
  "Drop Telepack on Horned Lizard",
  "Drop Telepack on Cave Mole",
  "Drop Telepack on Quillback",
  "Drop Telepack on Mantrap",
  "Drop Telepack on Tiki Man",
  "Drop Telepack on Witch Doctor",
  "Drop Telepack on Mosquito",
  "Drop Telepack on Monkey",
  "Drop Telepack on Hang Spider",
  "Drop Telepack on Giant Spider",
  "Drop Telepack on Fire Bug",
  "Drop Telepack on Imp",
  "Drop Telepack on Vampire",
  "Drop Telepack on Vlad",
  "Drop Telepack on Jiangshi",
  "Drop Telepack on Jiangshi Assassin",
  "Drop Telepack on Flying Fish",
  "Drop Telepack on Octopy",
  "Drop Telepack on Hermit Crab",
  "Drop Telepack on Pangxie",
  "Drop Telepack on Great Humphead",
  "Drop Telepack on Crocman",
  "Drop Telepack on Cobra",
  "Drop Telepack on Mummy",
  "Drop Telepack on Sorceress",
  "Drop Telepack on Cat Mummy",
  "Drop Telepack on Necromancer",
  "Drop Telepack on Anubis",
  "Drop Telepack on UFO",
  "Drop Telepack on Alien",
  "Drop Telepack on Yeti",
  "Drop Telepack on Yeti King",
  "Drop Telepack on Yeti Queen",
  "Drop Telepack on Lahamu",
  "Drop Telepack on Olmite",
  "Drop Telepack on Lamassu",
  "Drop Telepack on Tiamat",
  "Drop Telepack on Tadpole",
  "Drop Telepack on Frog",
  "Drop Telepack on Fire Frog",
  "Drop Telepack on Goliath Frog",
  "Drop Telepack on Grub",
  "Drop Telepack on Giant Fly",
  "Drop Telepack on Hundun",
  "Drop Telepack on Eggplant Minister",
  "Drop Telepack on Eggplup",
  "Drop Telepack on Scorpion",
  "Drop Telepack on Bee",
  "Drop Telepack on Queen Bee",
  "Drop Telepack on Scarab",
  "Drop Telepack on Golden Monkey",
  "Drop Telepack on Leprechaun",
  "Drop Telepack on Pet",
  "Drop Telepack on Cave Turkey",
  "Drop Telepack on Rock Dog",
  "Drop Telepack on Axolotl",
  "Drop Telepack on Qilin",
  "Drop Hoverpack on Snake",
  "Drop Hoverpack on Spider",
  "Drop Hoverpack on Bat",
  "Drop Hoverpack on Caveman",
  "Drop Hoverpack on Skeleton",
  "Drop Hoverpack on Horned Lizard",
  "Drop Hoverpack on Cave Mole",
  "Drop Hoverpack on Quillback",
  "Drop Hoverpack on Mantrap",
  "Drop Hoverpack on Tiki Man",
  "Drop Hoverpack on Witch Doctor",
  "Drop Hoverpack on Mosquito",
  "Drop Hoverpack on Monkey",
  "Drop Hoverpack on Hang Spider",
  "Drop Hoverpack on Giant Spider",
  "Drop Hoverpack on Fire Bug",
  "Drop Hoverpack on Imp",
  "Drop Hoverpack on Vampire",
  "Drop Hoverpack on Vlad",
  "Drop Hoverpack on Jiangshi",
  "Drop Hoverpack on Jiangshi Assassin",
  "Drop Hoverpack on Flying Fish",
  "Drop Hoverpack on Octopy",
  "Drop Hoverpack on Hermit Crab",
  "Drop Hoverpack on Pangxie",
  "Drop Hoverpack on Great Humphead",
  "Drop Hoverpack on Crocman",
  "Drop Hoverpack on Cobra",
  "Drop Hoverpack on Mummy",
  "Drop Hoverpack on Sorceress",
  "Drop Hoverpack on Cat Mummy",
  "Drop Hoverpack on Necromancer",
  "Drop Hoverpack on Anubis",
  "Drop Hoverpack on UFO",
  "Drop Hoverpack on Alien",
  "Drop Hoverpack on Yeti",
  "Drop Hoverpack on Yeti King",
  "Drop Hoverpack on Yeti Queen",
  "Drop Hoverpack on Lahamu",
  "Drop Hoverpack on Olmite",
  "Drop Hoverpack on Lamassu",
  "Drop Hoverpack on Tiamat",
  "Drop Hoverpack on Tadpole",
  "Drop Hoverpack on Frog",
  "Drop Hoverpack on Fire Frog",
  "Drop Hoverpack on Goliath Frog",
  "Drop Hoverpack on Grub",
  "Drop Hoverpack on Giant Fly",
  "Drop Hoverpack on Hundun",
  "Drop Hoverpack on Eggplant Minister",
  "Drop Hoverpack on Eggplup",
  "Drop Hoverpack on Scorpion",
  "Drop Hoverpack on Bee",
  "Drop Hoverpack on Queen Bee",
  "Drop Hoverpack on Scarab",
  "Drop Hoverpack on Golden Monkey",
  "Drop Hoverpack on Leprechaun",
  "Drop Hoverpack on Pet",
  "Drop Hoverpack on Cave Turkey",
  "Drop Hoverpack on Rock Dog",
  "Drop Hoverpack on Axolotl",
  "Drop Hoverpack on Qilin",
  "Drop Powerpack on Snake",
  "Drop Powerpack on Spider",
  "Drop Powerpack on Bat",
  "Drop Powerpack on Caveman",
  "Drop Powerpack on Skeleton",
  "Drop Powerpack on Horned Lizard",
  "Drop Powerpack on Cave Mole",
  "Drop Powerpack on Quillback",
  "Drop Powerpack on Mantrap",
  "Drop Powerpack on Tiki Man",
  "Drop Powerpack on Witch Doctor",
  "Drop Powerpack on Mosquito",
  "Drop Powerpack on Monkey",
  "Drop Powerpack on Hang Spider",
  "Drop Powerpack on Giant Spider",
  "Drop Powerpack on Fire Bug",
  "Drop Powerpack on Imp",
  "Drop Powerpack on Vampire",
  "Drop Powerpack on Vlad",
  "Drop Powerpack on Jiangshi",
  "Drop Powerpack on Jiangshi Assassin",
  "Drop Powerpack on Flying Fish",
  "Drop Powerpack on Octopy",
  "Drop Powerpack on Hermit Crab",
  "Drop Powerpack on Pangxie",
  "Drop Powerpack on Great Humphead",
  "Drop Powerpack on Crocman",
  "Drop Powerpack on Cobra",
  "Drop Powerpack on Mummy",
  "Drop Powerpack on Sorceress",
  "Drop Powerpack on Cat Mummy",
  "Drop Powerpack on Necromancer",
  "Drop Powerpack on Anubis",
  "Drop Powerpack on UFO",
  "Drop Powerpack on Alien",
  "Drop Powerpack on Yeti",
  "Drop Powerpack on Yeti King",
  "Drop Powerpack on Yeti Queen",
  "Drop Powerpack on Lahamu",
  "Drop Powerpack on Olmite",
  "Drop Powerpack on Lamassu",
  "Drop Powerpack on Tiamat",
  "Drop Powerpack on Tadpole",
  "Drop Powerpack on Frog",
  "Drop Powerpack on Fire Frog",
  "Drop Powerpack on Goliath Frog",
  "Drop Powerpack on Grub",
  "Drop Powerpack on Giant Fly",
  "Drop Powerpack on Hundun",
  "Drop Powerpack on Eggplant Minister",
  "Drop Powerpack on Eggplup",
  "Drop Powerpack on Scorpion",
  "Drop Powerpack on Bee",
  "Drop Powerpack on Queen Bee",
  "Drop Powerpack on Scarab",
  "Drop Powerpack on Golden Monkey",
  "Drop Powerpack on Leprechaun",
  "Drop Powerpack on Pet",
  "Drop Powerpack on Cave Turkey",
  "Drop Powerpack on Rock Dog",
  "Drop Powerpack on Axolotl",
  "Drop Powerpack on Qilin",
  "Drop Cape on Hired Hand",
  "Drop Cape on Eggplant Child",
  "Drop Cape on Shopkeeper",
  "Drop Cape on Tun",
  "Drop Cape on Yang",
  "Drop Cape on Madame Tusk",
  "Drop Cape on Tusk's Bodyguard",
  "Drop Cape on Waddler",
  "Drop Cape on Caveman Shopkeeper",
  "Drop Cape on Ghist Shopkeeper",
  "Drop Cape on Van Horsing",
  "Drop Cape on Parsley",
  "Drop Cape on Parsnip",
  "Drop Cape on Parmesan",
  "Drop Cape on Sparrow",
  "Drop Cape on Beg",
  "Drop Cape on Eggplant King",
  "Drop Vlad's Cape on Hired Hand",
  "Drop Vlad's Cape on Eggplant Child",
  "Drop Vlad's Cape on Shopkeeper",
  "Drop Vlad's Cape on Tun",
  "Drop Vlad's Cape on Yang",
  "Drop Vlad's Cape on Madame Tusk",
  "Drop Vlad's Cape on Tusk's Bodyguard",
  "Drop Vlad's Cape on Waddler",
  "Drop Vlad's Cape on Caveman Shopkeeper",
  "Drop Vlad's Cape on Ghist Shopkeeper",
  "Drop Vlad's Cape on Van Horsing",
  "Drop Vlad's Cape on Parsley",
  "Drop Vlad's Cape on Parsnip",
  "Drop Vlad's Cape on Parmesan",
  "Drop Vlad's Cape on Sparrow",
  "Drop Vlad's Cape on Beg",
  "Drop Vlad's Cape on Eggplant King",
  "Drop Jetpack on Hired Hand",
  "Drop Jetpack on Eggplant Child",
  "Drop Jetpack on Shopkeeper",
  "Drop Jetpack on Tun",
  "Drop Jetpack on Yang",
  "Drop Jetpack on Madame Tusk",
  "Drop Jetpack on Tusk's Bodyguard",
  "Drop Jetpack on Waddler",
  "Drop Jetpack on Caveman Shopkeeper",
  "Drop Jetpack on Ghist Shopkeeper",
  "Drop Jetpack on Van Horsing",
  "Drop Jetpack on Parsley",
  "Drop Jetpack on Parsnip",
  "Drop Jetpack on Parmesan",
  "Drop Jetpack on Sparrow",
  "Drop Jetpack on Beg",
  "Drop Jetpack on Eggplant King",
  "Drop Telepack on Hired Hand",
  "Drop Telepack on Eggplant Child",
  "Drop Telepack on Shopkeeper",
  "Drop Telepack on Tun",
  "Drop Telepack on Yang",
  "Drop Telepack on Madame Tusk",
  "Drop Telepack on Tusk's Bodyguard",
  "Drop Telepack on Waddler",
  "Drop Telepack on Caveman Shopkeeper",
  "Drop Telepack on Ghist Shopkeeper",
  "Drop Telepack on Van Horsing",
  "Drop Telepack on Parsley",
  "Drop Telepack on Parsnip",
  "Drop Telepack on Parmesan",
  "Drop Telepack on Sparrow",
  "Drop Telepack on Beg",
  "Drop Telepack on Eggplant King",
  "Drop Hoverpack on Hired Hand",
  "Drop Hoverpack on Eggplant Child",
  "Drop Hoverpack on Shopkeeper",
  "Drop Hoverpack on Tun",
  "Drop Hoverpack on Yang",
  "Drop Hoverpack on Madame Tusk",
  "Drop Hoverpack on Tusk's Bodyguard",
  "Drop Hoverpack on Waddler",
  "Drop Hoverpack on Caveman Shopkeeper",
  "Drop Hoverpack on Ghist Shopkeeper",
  "Drop Hoverpack on Van Horsing",
  "Drop Hoverpack on Parsley",
  "Drop Hoverpack on Parsnip",
  "Drop Hoverpack on Parmesan",
  "Drop Hoverpack on Sparrow",
  "Drop Hoverpack on Beg",
  "Drop Hoverpack on Eggplant King",
  "Drop Powerpack on Hired Hand",
  "Drop Powerpack on Eggplant Child",
  "Drop Powerpack on Shopkeeper",
  "Drop Powerpack on Tun",
  "Drop Powerpack on Yang",
  "Drop Powerpack on Madame Tusk",
  "Drop Powerpack on Tusk's Bodyguard",
  "Drop Powerpack on Waddler",
  "Drop Powerpack on Caveman Shopkeeper",
  "Drop Powerpack on Ghist Shopkeeper",
  "Drop Powerpack on Van Horsing",
  "Drop Powerpack on Parsley",
  "Drop Powerpack on Parsnip",
  "Drop Powerpack on Parmesan",
  "Drop Powerpack on Sparrow",
  "Drop Powerpack on Beg",
  "Drop Powerpack on Eggplant King",
  "Drop Hired Hand in lava",
  "Drop Eggplant Child in lava",
  "Drop Shopkeeper in lava",
  "Drop Tun in lava",
  "Drop Yang in lava",
  "Drop Caveman in lava",
  "Drop Cave Mole in lava",
  "Drop Tiki Man in lava",
  "Drop Witch Doctor in lava",
  "Drop Octopy in lava",
  "Drop Hermit Crab in lava",
  "Drop Crocman in lava",
  "Drop Sorceress in lava",
  "Drop Necromancer in lava",
  "Drop Yeti in lava",
  "Drop Olmite in lava",
  "Drop Leprechaun in lava",
  "Drop Pet in lava",
  "Drop Cave Turkey in lava",
  "Drop Rock Dog in lava",
  "Drop Axolotl in lava",
  "Drop Qilin in lava",
  "Drop Crossbow in lava",
  "Drop Hou Yi's Bow in lava",
  "Drop Wooden Shield in lava",
  "Drop Metal Shield in lava",
  "Drop Idol in lava",
  "Drop The Tusk Idol in lava",
  "Drop Curse Pot in lava",
  "Drop Ushabti in lava",
  "Drop Eggplant in lava",
  "Drop Gold Key in lava",
  "Drop Metal Key in lava",
  "Drop Stone Arrow in lava",
  "Drop Metal Arrow in lava",
  "Drop Broken Arrow in lava",
  "Drop Torch in lava",
  "Drop Ball and Chain in lava",
  "Drop Pot of Gold in lava",
  "Drop Dice in lava",
  "Drop Crate in lava",
  "Drop Present in lava",
  "Drop Chest in lava",
  "Drop Ball and Chain in lava",
  "Drop Hired Hand in ice caves void",
  "Drop Eggplant Child in ice caves void",
  "Drop Shopkeeper in ice caves void",
  "Drop Tun in ice caves void",
  "Drop Yang in ice caves void",
  "Drop Caveman in ice caves void",
  "Drop Cave Mole in ice caves void",
  "Drop Tiki Man in ice caves void",
  "Drop Witch Doctor in ice caves void",
  "Drop Octopy in ice caves void",
  "Drop Hermit Crab in ice caves void",
  "Drop Crocman in ice caves void",
  "Drop Sorceress in ice caves void",
  "Drop Necromancer in ice caves void",
  "Drop Yeti in ice caves void",
  "Drop Olmite in ice caves void",
  "Drop Leprechaun in ice caves void",
  "Drop Pet in ice caves void",
  "Drop Cave Turkey in ice caves void",
  "Drop Rock Dog in ice caves void",
  "Drop Axolotl in ice caves void",
  "Drop Qilin in ice caves void",
  "Drop Crossbow in ice caves void",
  "Drop Hou Yi's Bow in ice caves void",
  "Drop Wooden Shield in ice caves void",
  "Drop Metal Shield in ice caves void",
  "Drop Idol in ice caves void",
  "Drop The Tusk Idol in ice caves void",
  "Drop Curse Pot in ice caves void",
  "Drop Ushabti in ice caves void",
  "Drop Eggplant in ice caves void",
  "Drop Gold Key in ice caves void",
  "Drop Metal Key in ice caves void",
  "Drop Stone Arrow in ice caves void",
  "Drop Metal Arrow in ice caves void",
  "Drop Broken Arrow in ice caves void",
  "Drop Torch in ice caves void",
  "Drop Ball and Chain in ice caves void",
  "Drop Pot of Gold in ice caves void",
  "Drop Dice in ice caves void",
  "Drop Crate in ice caves void",
  "Drop Present in ice caves void",
  "Drop Chest in ice caves void",
  "Drop Ball and Chain in ice caves void",
  "Complete Any% run",
  "Complete Sunken City% run",
  "Complete Cosmic Ocean% run",
  "Complete Low% run",
  "Complete Low% Jungle/Temple run",
  "Complete Pacifist Low% run",
  "Complete No Teleporter Any% run",
  "Complete No Teleporter Sunken City% run",
  "Complete No Teleporter Eggplant% run",
  "Complete No Gold run",
  "Complete No Gold Low% run",
  "Complete Abzu% run",
  "Complete Duat% run",
  "Complete No Teleporter Abzu% run",
  "Complete No Teleporter Duat% run",
  "Complete Chain Low% Abzu run",
  "Complete Chain Low% Duat run",
  "Complete Low% Volcana/Temple run",
  "Complete Low% Sunken City run",
  "Complete No Gold Low% Sunken City run",
  "Complete No Teleporter No Gold run",
  "Complete No Gold Sunken City% run",
  "Complete No Teleporter No Gold Sunken City% run",
  "Complete No Gold Abzu% run",
  "Complete No Gold Duat% run",
  "Complete No Gold Chain Low% Abzu run",
  "Complete No Gold Chain Low% Duat run",
  "Complete Eggplant% run",
  "Complete Low% Eggplant run",
  "Complete No Gold Eggplant% run",
  "Complete No Gold Low% Eggplant run",
  "Complete No Teleporter No Gold Eggplant% run",
  "Complete Eggplant% Abzu run",
  "Complete Eggplant% Duat run",
  "Complete No Teleporter Eggplant% Abzu run",
  "Complete No Teleporter Eggplant% Duat run",
  "Complete Chain Low% Eggplant Abzu run",
  "Complete Chain Low% Eggplant Duat run",
  "Complete No Gold Chain Low% Eggplant Abzu run",
  "Complete No Gold Chain Low% Eggplant Duat run",
  "Complete Millionaire run",
  "Complete No Teleporter Millionaire run",
  "Complete Low% Millionaire run",
  "Complete No% run",
  "Complete No% Sunken City run",
  "Complete Tutorial% run",
  "Complete Tutorial% No Skips run",
  "Complete Ice Caves Shortcut% run",
  "Complete Pacifist Ice Caves Shortcut% run",
  "Complete Ice Caves Shortcut% Millionaire run",
  "Complete Ice Caves Shortcut Sunken City% run",
  "Complete Pacifist run",
  "Complete Pacifist Sunken City% run",
  "Complete Pacifist Low% run",
  "Complete No Teleporter Pacifist run",
  "Complete No Teleporter Pacifist Sunken City% run",
  "Complete No Gold Pacifist run",
  "Complete No Gold Pacifist Sunken City% run",
  "Complete No Gold Pacifist Low% run",
  "Complete Pacifist Low% Sunken City run",
  "Complete No Gold Pacifist Low% Sunken City run",
  "Complete Pacifist Abzu% run",
  "Complete Pacifist Duat% run",
  "Complete Pacifist Chain Low% Abzu run",
  "Complete Pacifist Chain Low% Duat run",
  "Complete No Gold Pacifist Chain Low% Abzu run",
  "Complete No Gold Pacifist Chain Low% Duat run",
  "Complete Pacifist Eggplant% run",
  "Complete Pacifist Low% Eggplant run",
  "Complete No Gold Pacifist Eggplant% run",
  "Complete No Gold Pacifist Low% Eggplant run",
  "Complete Pacifist Chain Low% Eggplant Abzu run",
  "Complete Pacifist Chain Low% Eggplant Duat run",
  "Complete No Gold Pacifist Chain Low% Eggplant Abzu run",
  "Complete No Gold Pacifist Chain Low% Eggplant Duat run",
  "Complete Pacifist No% run",
  "Complete Pacifist No% Sunken City run",
  "Complete Pacifist Ice Caves Shortcut% run",
  "Complete Pacifist Ice Caves Shortcut Sunken City% run",
  "Complete Ice Caves Shortcut Any% run",
  "Complete Crushabti% run",
  "Complete Axolotl% run",
  "Complete Turkey% run",
  "Complete Slow% run",
  "Complete True Crown Low% run",
  "Complete Keyamat run",
  "Complete Rope% run",
  "Complete Ice Caves Shortcut Eggplant% run",
  "Complete Legendary Meal% run",
  "Clone yourself",
  "Kill Eggplant King as Tina",
  "Meet Sparrow as Dirk",
];